### ISSUE TITLE
1.9.0版本沒打开

### ISSUE THREAD

**Issue by LuckyLi706** [Leon406/ToolsFx#14]
## 问题日志
`C:\Users\test\Desktop\ToolsFx-1.9.0-jdk8>ToolsFx.bat
check plugin: C:\Users\test\Desktop\ToolsFx-1.9.0-jdk8\plugin
Exception in Application start method
Exception in Application stop method
鍗佹湀 13, 2021 10:08:33 涓婂崍 tornadofx.DefaultErrorHandler uncaughtException
涓ラ噸: Uncaught error
java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:875)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$147(LauncherImpl.java:157)
        at com.sun.javafx.application.LauncherImpl$$Lambda$1/1078694789.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: java.util.ServiceLoader.findFirst()Ljava/util/Optional;
        at me.leon.view.Home$root$1.invoke(Home.kt:51)
        at me.leon.view.Home$root$1.invoke(Home.kt:21)
        at tornadofx.TabPaneKt.tabpane(TabPane.kt:196)
        at me.leon.view.Home.<init>(Home.kt:21)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at java.lang.Class.newInstance(Class.java:433)
        at tornadofx.FXKt.find(FX.kt:434)
        at tornadofx.FXKt.find$default(FX.kt:423)
        at tornadofx.App.start(App.kt:83)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(LauncherImpl.java:821)
        at com.sun.javafx.application.LauncherImpl$$Lambda$51/590911094.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(PlatformImpl.java:323)
        at com.sun.javafx.application.PlatformImpl$$Lambda$46/151860546.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl$$Lambda$48/1232144107.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl$$Lambda$47/745867717.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$141(WinApplication.java:102)
        at com.sun.glass.ui.win.WinApplication$$Lambda$38/1819011905.run(Unknown Source)
        ... 1 more`

## 环境和版本
+ 使用的是ToolsFx-1.9.0-jdk8.zip
+ 本地环境win10，jdk版本1.8.0_20

## 思考
我记得JavaFX可以打包成exe、dmg的，为啥不脱离Java环境。

**Comment by Leon406** [comment]
你是覆盖安装,还是全新安装
