### ISSUE TITLE
Mac 环境无法打开?

### ISSUE THREAD

**Issue by lxthyme** [Leon406/ToolsFx#15]
系统版本: Mac Pro macOS Big Sur 11.6

ToolsFx-1.9.0-jdk8-fix 和 ToolsFx-1.9.0-jdk8 lib 目录下的 ToolsFx-1.9.0.jar 都试过

报错:
      ./ToolsFx-1.9.0.jar中没有主清单属性

**Comment by Leon406** [comment]
提供下完整报错信息

**Comment by lxthyme** [comment]
ToolsFx-1.9.0-jdk8 目录下只有这几个文件:
```bash
ToolsFx           
ToolsFx.bat        
ToolsFx.properties ToolsFx.vbs        
lib
```

**Comment by Leon406** [comment]
第一个 ToolsFx,
能双击就双击,不能话执行以下命令
bash   ToolsFx

**Comment by lxthyme** [comment]
@Leon406  报这个错误
```bash
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at me.leon.MainKt.main(main.kt:9)
	at me.leon.MainKt.main(main.kt)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 more
```

**Comment by lxthyme** [comment]
`java -version`

```bash
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```

**Comment by Leon406** [comment]
https://leon.lanzouw.com/iWXMGv9djqd
配置jdk11 以上环境变量和javafx的环境变量

**Comment by lxthyme** [comment]
可以了, 非常感谢~

**Comment by Leon406** [comment]
好的,我关闭issue了
